<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.88.1">
    <title>Dashboard Template · Bootstrap v5.1</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.1/examples/dashboard/">

    

    <!-- Bootstrap core CSS -->
    <link href="../node_modules/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" crossorigin="anonymous">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>

    
    <!-- Custom styles for this template -->
    <link href="./assets/css/dashboard.css" rel="stylesheet">
  </head>
  <body>
    
<?php require_once"/var/www/html/app/views/dashboard/header.phtml";?>

<div class="container-fluid">
  <div class="row">
  <?php require_once"/var/www/html/app/views/dashboard/sidebar.phtml";?>

    <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
      <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2"><?php echo $this->locale->_('Products'); ?></h1>
        <div class="btn-toolbar mb-2 mb-md-0">
          <div class="btn-group me-2">
            
            <button type="button" class="btn btn-sm btn-outline-secondary"><?php echo $this->locale->_('Share'); ?></button>
            <button type="button" class="btn btn-sm btn-outline-secondary"><?php echo $this->locale->_('Export'); ?></button>
          </div>
          <button type="button" class="btn btn-sm btn-outline-secondary dropdown-toggle">
            <span data-feather="calendar"></span>
            <?php echo $this->locale->_('This week'); ?>
          </button>
        </div>
      </div>
      <form action="" method='get'>
      <div for="drop down" style="padding-top: 40px;">
              <label for="role" class="font-weight-bold text-primary">Choose a Language:</label>

              <select name="locale" onchange = "this.form.submit()" >
                  <option value="en">List</option>   
                  <option value="en">English</option>
                <option value="fr">French</option>
                <option value="hn">Hindi</option>
                <input type="hidden" name="bearer" value="<?php echo $_GET['bearer']?>">
              </select>

      </div>
      <form class="row row-cols-lg-auto g-3 align-items-center">
        <div class="col-12">
          <label class="visually-hidden" for="inlineFormInputGroupUsername"><?php echo $this->locale->_('Search'); ?></label>
          <div class="input-group">
            <input type="text" class="form-control" id="inlineFormInputGroupUsername" placeholder="Enter id,name...">
          </div>
        </div>
      
        
      
        <div class="col-12">
          <button type="submit" class="btn btn-primary"><?php echo $this->locale->_('Search'); ?></button>
        </div>
        <div class="col-12">
          <a class="btn btn-success" href="/product/addproduct/?bearer=<?php echo $_GET['bearer'];?>"><?php echo $this->locale->_('Add Product'); ?></a>
        </div>
      </form>
      <div class="table-responsive">
        <table class="table table-striped table-sm">
          <thead>
            <tr>
              <th scope="col">Product_ID</th>
              <th scope="col">Product Name</th>
              <th scope="col">Product Price</th>
              <th scope="col">Product Category</th>
              <th scope="col">Action</th>
            </tr>
          </thead>
          <tbody>
            <?php echo $display; ?>
            <!-- <tr>
              <td>1,001</td>
              <td>random</td>
              <td>data</td>
              <td>placeholder</td>
              <td><a href="#">Edit</a>&nbsp;<a href="#">Delete</a></td>
            </tr> -->
           
          </tbody>
        </table>
        <nav aria-label="Page navigation example">
            <ul class="pagination">
            <?php
                          //$page=$data[1];
                          $last=$page->getLast();
                          $disp='';
                          if($page->getCurrent() != 1)
                          $disp.=' <li class="page-item"><a class="page-link" href="/product?page='.$page->getPrevious().'&bearer='.$this->request->getQuery('bearer').'">Previous</a></li>';
                          // $j=1;
                          for ($i=1;$i<=$last;$i++)
                          {
                            $disp.='<li class="page-item"><a class="page-link" href="/product?page='.$i.'&bearer='.$this->request->getQuery('bearer').'">'.$i.'</a></li>';

                          }
                          if($page->getCurrent() != $page->getLast())
                          $disp.=' <li class="page-item"><a class="page-link" href="/product?page='.$page->getNext().'&bearer='.$this->request->getQuery('bearer').'">Next</a></li>';
                          echo $disp;
                    ?>
            </ul>
          </nav>
      </div>
    </main>
  </div>
</div>


    <script src="../node_modules/bootstrap/dist/js/bootstrap.bundle.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </body>
</html>